spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  docker:
    compose:
      lifecycle-management: start-and-stop
      start:
        command: up
      stop:
        command: down

